---
ACCESS_TOKEN_EXPIRES_IN: 1h
REFRESH_TOKEN_EXPIRES_IN: 7d
JWT_ACCESS_TOKEN_SECRET: "----- YOUR KEY -----"
JWT_REFRESH_TOKEN_SECRET: "----- YOUR KEY -----"
DATABASE_URL: "postgresql://neondb_owner:npg_2bPwyIL4KJvE@ep-late-dream-an2x7oke-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
